package dev.tnclark8012.dogshow.shared;

import java.util.ArrayList;

public enum Breeds {
	//****BEGIN FSS****
	APPENZELLER_SENNENHUNDE(BreedGroup.FSS, "Appenzeller Sennenhunde"),
	BARBET(BreedGroup.FSS, "Barbet"),
	BERGER_PICARD(BreedGroup.FSS, "Berger Picard"),
	BOERBOEL(BreedGroup.FSS, "Boerboel"),
	BOLOGNESE(BreedGroup.FSS, "Bolognese"),
	BRACCO_ITALIANO(BreedGroup.FSS, "Bracco Italiano"),
	BRAQUE_DU_BOURBONNAIS(BreedGroup.FSS, "Braque du Bourbonnais"),
	CATAHOULA_LEOPARD_DOG(BreedGroup.FSS, "Catahoula Leopard Dog"),
	CAUCASIAN_OVCHARKA(BreedGroup.FSS, "Caucasian Ovcharka"),
	CENTRAL_ASIAN_SHEPHERD_DOG(BreedGroup.FSS, "Central Asian Shepherd Dog"),
	CIRNECO_DELL_ETNA(BreedGroup.FSS, "Cirneco dell’Etna"),
	COTON_DE_TULEAR(BreedGroup.FSS, "Coton de Tulear"),
	CZECHOSLOVAKIAN_VLCAK(BreedGroup.FSS, "Czechoslovakian Vlcak"),
	DANISH_SWEDISH_FARMDOG(BreedGroup.FSS, "Danish–Swedish Farmdog"),
	DRENTSCHE_PATRIJSHOND(BreedGroup.FSS, "Drentsche Patrijshond"),
	ESTRELA_MOUNTAIN_DOG(BreedGroup.FSS, "Estrela Mountain Dog"),
	EURASIER(BreedGroup.FSS, "Eurasier"),
	GERMAN_LONGHAIRED_POINTER(BreedGroup.FSS, "German Longhaired Pointer"),
	GERMAN_SPITZ(BreedGroup.FSS, "German Spitz"),
	GRAND_BASSET_GRIFFON_VENDEEN(BreedGroup.FSS, "Grand Basset Griffon Vendeen"),
	HAMILTONSTOVARE(BreedGroup.FSS, "Hamiltonstovare"),
	HOVAWART(BreedGroup.FSS, "Hovawart"),
	JINDO(BreedGroup.FSS, "Jindo"),
	KAI_KEN(BreedGroup.FSS, "Kai Ken"),
	KARELIAN_BEAR_DOG(BreedGroup.FSS, "Karelian Bear Dog"),
	KISHU_KEN(BreedGroup.FSS, "Kishu Ken"),
	KOOIKERHONDJE(BreedGroup.FSS, "Kooikerhondje"),
	LAGOTTO_ROMAGNOLO(BreedGroup.FSS, "Lagotto Romagnolo"),
	LANCASHIRE_HEELER(BreedGroup.FSS, "Lancashire Heeler"),
	MINIATURE_AMERICAN_SHEPHERD(BreedGroup.FSS, "Miniature American Shepherd"),
	MUDI(BreedGroup.FSS, "Mudi"),
	NORRBOTTENSPETS(BreedGroup.FSS, "Norrbottenspets"),
	PERRO_DE_PRESA_CANARIO(BreedGroup.FSS, "Perro de Presa Canario"),
	PORTUGUESE_PODENGO(BreedGroup.FSS, "Portuguese Podengo"),
	PORTUGUESE_POINTER(BreedGroup.FSS, "Portuguese Pointer"),
	RAFEIRO_DO_ALENTJO(BreedGroup.FSS, "Rafeiro do Alentjo"),
	RUSSIAN_TOY(BreedGroup.FSS, "Russian Toy"),
	SCHAPENDOES(BreedGroup.FSS, "Schapendoes"),
	SLOVENSKY_CUVAC(BreedGroup.FSS, "Slovensky Cuvac"),
	SMALL_MUNSTERLANDER_POINTER(BreedGroup.FSS, "Small Munsterlander Pointer"),
	SPANISH_MASTIFF(BreedGroup.FSS, "Spanish Mastiff"),
	SPANISH_WATER_DOG(BreedGroup.FSS, "Spanish Water Dog"),
	STABYHOUN(BreedGroup.FSS, "Stabyhoun"),
	SWEDISH_LAPPHUND(BreedGroup.FSS, "Swedish Lapphund"),
	THAI_RIDGEBACK(BreedGroup.FSS, "Thai Ridgeback"),
	TOSA(BreedGroup.FSS, "Tosa"),
	TREEING_TENNESSEE_BRINDLE(BreedGroup.FSS, "Treeing Tennessee Brindle"),
	//****END FSS****
	//****BEGIN HERDING****
	AUSTRALIAN_CATTLE_DOG(BreedGroup.HERDING, "Australian Cattle Dog"),
	AUSTRALIAN_SHEPHERD(BreedGroup.HERDING, "Australian Shepherd"),
	BEARDED_COLLIE(BreedGroup.HERDING, "Bearded Collie"),
	BEAUCERON(BreedGroup.HERDING, "Beauceron"),
	BELGIAN_MALINOIS(BreedGroup.HERDING, "Belgian Malinois"),
	BELGIAN_SHEEPDOG(BreedGroup.HERDING, "Belgian Sheepdog"),
	BELGIAN_TERVUREN(BreedGroup.HERDING, "Belgian Tervuren"),
	BORDER_COLLIE(BreedGroup.HERDING, "Border Collie"),
	BOUVIER_DES_FLANDRES(BreedGroup.HERDING, "Bouvier des Flandres"),
	BRIARD(BreedGroup.HERDING, "Briard"),
	CANAAN_DOG(BreedGroup.HERDING, "Canaan Dog"),
	COLLIE_ROUGH(BreedGroup.HERDING, "Collie (Rough)"),
	COLLIE_SMOOTH(BreedGroup.HERDING, "Collie (Smooth)"),
	ENTLEBUCHER_MOUNTAIN_DOG(BreedGroup.HERDING, "Entlebucher Mountain Dog"),
	FINNISH_LAPPHUND(BreedGroup.HERDING, "Finnish Lapphund"),
	GERMAN_SHEPHERD_DOG(BreedGroup.HERDING, "German Shepherd Dog"),
	ICELANDIC_SHEEPDOG(BreedGroup.HERDING, "Icelandic Sheepdog"),
	NORWEGIAN_BUHUND(BreedGroup.HERDING, "Norwegian Buhund"),
	OLD_ENGLISH_SHEEPDOG(BreedGroup.HERDING, "Old English Sheepdog"),
	POLISH_LOWLAND_SHEEPDOG(BreedGroup.HERDING, "Polish Lowland Sheepdog"),
	PULI(BreedGroup.HERDING, "Puli"),
	PYRENEAN_SHEPHERD(BreedGroup.HERDING, "Pyrenean Shepherd"),
	SHETLAND_SHEEPDOG(BreedGroup.HERDING, "Shetland Sheepdog"),
	SWEDISH_VALLHUND(BreedGroup.HERDING, "Swedish Vallhund"),
	CARDIGAN_WELSH_CORGI(BreedGroup.HERDING, "Cardigan Welsh Corgi"),
	PEMBROKE_WELSH_CORGI(BreedGroup.HERDING, "Pembroke Welsh Corgi"),
	//****END HERDING****
	//****BEGIN HOUND****
	AFGHAN_HOUND(BreedGroup.HOUND, "Afghan Hound"),
	AMERICAN_ENGLISH_COONHOUND(BreedGroup.HOUND, "American English Coonhound"),
	AMERICAN_FOXHOUND(BreedGroup.HOUND, "American Foxhound"),
	BASENJI(BreedGroup.HOUND, "Basenji"),
	BASSET_HOUND(BreedGroup.HOUND, "Basset Hound"),
	BEAGLE_13(BreedGroup.HOUND, "Beagle (13”)"),
	BEAGLE_15(BreedGroup.HOUND, "Beagle (15”)"),
	BLACK_AND_TAN_COONHOUND(BreedGroup.HOUND, "Black and Tan Coonhound"),
	BLOODHOUND(BreedGroup.HOUND, "Bloodhound"),
	BORZOI(BreedGroup.HOUND, "Borzoi"),
	DACHSHUND_LONGHAIRED(BreedGroup.HOUND, "Dachshund (Longhaired)"),
	DACHSHUND_SMOOTH(BreedGroup.HOUND, "Dachshund (Smooth)"),
	DACHSHUND_WIREHAIRED(BreedGroup.HOUND, "Dachshund (Wirehaired)"),
	ENGLISH_FOXHOUND(BreedGroup.HOUND, "English Foxhound"),
	GREYHOUND(BreedGroup.HOUND, "Greyhound"),
	HARRIER(BreedGroup.HOUND, "Harrier"),
	IBIZAN_HOUND(BreedGroup.HOUND, "Ibizan Hound"),
	IRISH_WOLFHOUND(BreedGroup.HOUND, "Irish Wolfhound"),
	NORWEGIAN_ELKHOUND(BreedGroup.HOUND, "Norwegian Elkhound"),
	OTTERHOUND(BreedGroup.HOUND, "Otterhound"),
	PETIT_BASSET_GRIFFON_VENDÉEN(BreedGroup.HOUND, "Petit Basset Griffon Vendéen"),
	PHARAOH_HOUND(BreedGroup.HOUND, "Pharaoh Hound"),
	PLOTT(BreedGroup.HOUND, "Plott"),
	RHODESIAN_RIDGEBACK(BreedGroup.HOUND, "Rhodesian Ridgeback"),
	SALUKI(BreedGroup.HOUND, "Saluki"),
	SCOTTISH_DEERHOUND(BreedGroup.HOUND, "Scottish Deerhound"),
	WHIPPET(BreedGroup.HOUND, "Whippet"),
	BLUETICK_COONHOUND(BreedGroup.HOUND, "Bluetick Coonhound"),
	REDBONE_COONHOUND(BreedGroup.HOUND, "Redbone Coonhound"),
	//****END HOUND****
	//****BEGIN MISCELLANEOUS****
	AZAWAKH(BreedGroup.MISCELLANEOUS, "Azawakh"),
	BELGIAN_LAEKENOIS(BreedGroup.MISCELLANEOUS, "Belgian Laekenois"),
	BERGAMASCO(BreedGroup.MISCELLANEOUS, "Bergamasco"),
	BOERGOEL(BreedGroup.MISCELLANEOUS, "Boergoel"),
	CHINOOK(BreedGroup.MISCELLANEOUS, "Chinook"),
	DOGO_ARGENTINO(BreedGroup.MISCELLANEOUS, "Dogo Argentino"),
	PERUVIAN_INCA_ORCHID(BreedGroup.MISCELLANEOUS, "Peruvian Inca Orchid"),
	PORTUGUESE_PODENGO_PEQUENO(BreedGroup.MISCELLANEOUS, "Portuguese Podengo Pequeno"),
	PUMI(BreedGroup.MISCELLANEOUS, "Pumi"),
	RAT_TERRIER(BreedGroup.MISCELLANEOUS, "Rat Terrier"),
	RUSSELL_TERRIER(BreedGroup.MISCELLANEOUS, "Russell Terrier"),
	SLOUGHI(BreedGroup.MISCELLANEOUS, "Sloughi"),
	TREEING_WALKER_COONHOUND(BreedGroup.MISCELLANEOUS, "Treeing Walker Coonhound"),
	WIREHAIRED_VIZSLA(BreedGroup.MISCELLANEOUS, "Wirehaired Vizsla"),
	//****END MISCELLANEOUS****
	//****BEGIN NON_SPORTING****
	AMERICAN_ESKIMO_DOG(BreedGroup.NON_SPORTING, "American Eskimo Dog"),
	BICHON_FRISE(BreedGroup.NON_SPORTING, "Bichon Frise"),
	BOSTON_TERRIER(BreedGroup.NON_SPORTING, "Boston Terrier"),
	BULLDOG(BreedGroup.NON_SPORTING, "Bulldog"),
	CHINESE_SHAR_PEI(BreedGroup.NON_SPORTING, "Chinese Shar-Pei"),
	CHOW_CHOW(BreedGroup.NON_SPORTING, "Chow Chow"),
	DALMATIAN(BreedGroup.NON_SPORTING, "Dalmatian"),
	FINNISH_SPITZ(BreedGroup.NON_SPORTING, "Finnish Spitz"),
	FRENCH_BULLDOG(BreedGroup.NON_SPORTING, "French Bulldog"),
	KEESHOND(BreedGroup.NON_SPORTING, "Keeshond"),
	LHASA_APSO(BreedGroup.NON_SPORTING, "Lhasa Apso"),
	LÖWCHEN(BreedGroup.NON_SPORTING, "Löwchen"),
	NORWEGIAN_LUNDEHUND(BreedGroup.NON_SPORTING, "Norwegian Lundehund"),
	POODLE_MINIATURE(BreedGroup.NON_SPORTING, "Poodle (Miniature)"),
	POODLE_STANDARD(BreedGroup.NON_SPORTING, "Poodle (Standard)"),
	SCHIPPERKE(BreedGroup.NON_SPORTING, "Schipperke"),
	SHIBA_INU(BreedGroup.NON_SPORTING, "Shiba Inu"),
	TIBETAN_SPANIEL(BreedGroup.NON_SPORTING, "Tibetan Spaniel"),
	TIBETAN_TERRIER_(BreedGroup.NON_SPORTING, "Tibetan Terrier "),
	XOLOITZCUINTLI(BreedGroup.NON_SPORTING, "Xoloitzcuintli"),
	//****END NON_SPORTING****
	//****BEGIN SPORTING****
	AMERICAN_WATER_SPANIEL(BreedGroup.SPORTING, "American Water Spaniel"),
	BOYKIN_SPANIEL(BreedGroup.SPORTING, "Boykin Spaniel"),
	BRITTANY(BreedGroup.SPORTING, "Brittany"),
	CHESAPEAKE_BAY_RETRIEVER(BreedGroup.SPORTING, "Chesapeake Bay Retriever"),
	CLUMBER_SPANIEL(BreedGroup.SPORTING, "Clumber Spaniel"),
	COCKER_SPANIEL_BLACK(BreedGroup.SPORTING, "Cocker Spaniel (Black)"),
	COCKER_SPANIEL_ASCOB(BreedGroup.SPORTING, "Cocker Spaniel (ASCOB)"),
	COCKER_SPANIEL_PARTI_COLOR(BreedGroup.SPORTING, "Cocker Spaniel (Parti-Color)"),
	CURLY_COATED_RETRIEVER(BreedGroup.SPORTING, "Curly-Coated Retriever"),
	ENGLISH_COCKER_SPANIEL(BreedGroup.SPORTING, "English Cocker Spaniel"),
	ENGLISH_SETTER(BreedGroup.SPORTING, "English Setter"),
	ENGLISH_SPRINGER_SPANIEL(BreedGroup.SPORTING, "English Springer Spaniel"),
	FIELD_SPANIEL(BreedGroup.SPORTING, "Field Spaniel"),
	FLAT_COATED_RETRIEVER(BreedGroup.SPORTING, "Flat-Coated Retriever"),
	GERMAN_SHORTHAIRED_POINTER(BreedGroup.SPORTING, "German Shorthaired Pointer"),
	GERMAN_WIREHAIRED_POINTER(BreedGroup.SPORTING, "German Wirehaired Pointer"),
	GOLDEN_RETRIEVER(BreedGroup.SPORTING, "Golden Retriever"),
	GORDON_SETTER(BreedGroup.SPORTING, "Gordon Setter"),
	IRISH_RED_AND_WHITE_SETTER(BreedGroup.SPORTING, "Irish Red & White Setter"),
	IRISH_SETTER(BreedGroup.SPORTING, "Irish Setter"),
	IRISH_WATER_SPANIEL(BreedGroup.SPORTING, "Irish Water Spaniel"),
	LABRADOR_RETRIEVER(BreedGroup.SPORTING, "Labrador Retriever"),
	NOVA_SCOTIA_DUCK_TOLLING_RETRIEVER(BreedGroup.SPORTING, "Nova Scotia Duck Tolling Retriever"),
	POINTER(BreedGroup.SPORTING, "Pointer"),
	SPINONE_ITALIANO(BreedGroup.SPORTING, "Spinone Italiano"),
	SUSSEX_SPANIEL(BreedGroup.SPORTING, "Sussex Spaniel"),
	VIZSLA(BreedGroup.SPORTING, "Vizsla"),
	WEIMARANER(BreedGroup.SPORTING, "Weimaraner"),
	WELSH_SPRINGER_SPANIEL(BreedGroup.SPORTING, "Welsh Springer Spaniel"),
	WIREHAIRED_POINTING_GRIFFON(BreedGroup.SPORTING, "Wirehaired Pointing Griffon"),
	//****END SPORTING****
	//****BEGIN TERRIER****
	AIREDALE_TERRIER(BreedGroup.TERRIER, "Airedale Terrier"),
	AMERICAN_STAFFORDSHIRE_TERRIER(BreedGroup.TERRIER, "American Staffordshire Terrier"),
	AUSTRALIAN_TERRIER(BreedGroup.TERRIER, "Australian Terrier"),
	BEDLINGTON_TERRIER(BreedGroup.TERRIER, "Bedlington Terrier"),
	BORDER_TERRIER(BreedGroup.TERRIER, "Border Terrier"),
	BULL_TERRIER_COLORED(BreedGroup.TERRIER, "Bull Terrier (Colored)"),
	BULL_TERRIER_WHITE(BreedGroup.TERRIER, "Bull Terrier (White)"),
	CAIRN_TERRIER(BreedGroup.TERRIER, "Cairn Terrier"),
	CESKY_TERRIER(BreedGroup.TERRIER, "Cesky Terrier"),
	DANDIE_DINMONT_TERRIER(BreedGroup.TERRIER, "Dandie Dinmont Terrier"),
	GLEN_OF_IMAAL_TERRIER(BreedGroup.TERRIER, "Glen of Imaal Terrier"),
	IRISH_TERRIER(BreedGroup.TERRIER, "Irish Terrier"),
	KERRY_BLUE_TERRIER(BreedGroup.TERRIER, "Kerry Blue Terrier"),
	LAKELAND_TERRIER(BreedGroup.TERRIER, "Lakeland Terrier"),
	MANCHESTER_TERRIER_STANDARD(BreedGroup.TERRIER, "Manchester Terrier (Standard)"),
	MINIATURE_BULL_TERRIER(BreedGroup.TERRIER, "Miniature Bull Terrier"),
	MINIATURE_SCHNAUZER(BreedGroup.TERRIER, "Miniature Schnauzer"),
	NORFOLK_TERRIER(BreedGroup.TERRIER, "Norfolk Terrier"),
	NORWICH_TERRIER(BreedGroup.TERRIER, "Norwich Terrier"),
	PARSON_RUSSELL_TERRIER(BreedGroup.TERRIER, "Parson Russell Terrier"),
	SCOTTISH_TERRIER(BreedGroup.TERRIER, "Scottish Terrier"),
	SEALYHAM_TERRIER(BreedGroup.TERRIER, "Sealyham Terrier"),
	SKYE_TERRIER(BreedGroup.TERRIER, "Skye Terrier"),
	SMOOTH_FOX_TERRIER(BreedGroup.TERRIER, "Smooth Fox Terrier"),
	SOFT_COATED_WHEATEN_TERRIER(BreedGroup.TERRIER, "Soft Coated Wheaten Terrier"),
	STAFFORDSHIRE_BULL_TERRIER(BreedGroup.TERRIER, "Staffordshire Bull Terrier"),
	WELSH_TERRIER(BreedGroup.TERRIER, "Welsh Terrier"),
	WEST_HIGHLAND_WHITE_TERRIER(BreedGroup.TERRIER, "West Highland White Terrier"),
	WIRE_FOX_TERRIER(BreedGroup.TERRIER, "Wire Fox Terrier"),
	//****END TERRIER****
	//****BEGIN TOY****
	AFFENPINSCHER(BreedGroup.TOY, "Affenpinscher"),
	BRUSSELS_GRIFFON(BreedGroup.TOY, "Brussels Griffon"),
	CAVALIER_KING_CHARLES_SPANIEL(BreedGroup.TOY, "Cavalier King Charles Spaniel"),
	CHIHUAHUA_LONG_COAT(BreedGroup.TOY, "Chihuahua (Long Coat)"),
	CHIHUAHUA_SMOOTH_COAT(BreedGroup.TOY, "Chihuahua (Smooth Coat)"),
	CHINESE_CRESTED(BreedGroup.TOY, "Chinese Crested"),
	ENGLISH_TOY_SPANIEL_BLENHEIM_AND_PRINCE_CHARLES(BreedGroup.TOY, "English Toy Spaniel (Blenheim and Prince Charles)"),
	ENGLISH_TOY_SPANIEL_KING_CHARLES_AND_RUBY(BreedGroup.TOY, "English Toy Spaniel (King Charles and Ruby)"),
	HAVANESE(BreedGroup.TOY, "Havanese"),
	ITALIAN_GREYHOUND(BreedGroup.TOY, "Italian Greyhound"),
	JAPANESE_CHIN(BreedGroup.TOY, "Japanese Chin"),
	MALTESE(BreedGroup.TOY, "Maltese"),
	MANCHESTER_TERRIER_TOY(BreedGroup.TOY, "Manchester Terrier (Toy)"),
	MINIATURE_PINSCHER(BreedGroup.TOY, "Miniature Pinscher"),
	PAPILLON(BreedGroup.TOY, "Papillon"),
	PEKINGESE(BreedGroup.TOY, "Pekingese"),
	POMERANIAN(BreedGroup.TOY, "Pomeranian"),
	POODLE_TOY(BreedGroup.TOY, "Poodle (Toy)"),
	PUG(BreedGroup.TOY, "Pug"),
	SHIH_TZU(BreedGroup.TOY, "Shih Tzu"),
	SILKY_TERRIER(BreedGroup.TOY, "Silky Terrier"),
	TOY_FOX_TERRIER(BreedGroup.TOY, "Toy Fox Terrier"),
	YORKSHIRE_TERRIER(BreedGroup.TOY, "Yorkshire Terrier"),
	//****END TOY****
	//****BEGIN WORKING****
	AKITA(BreedGroup.WORKING, "Akita"),
	ALASKAN_MALAMUTE(BreedGroup.WORKING, "Alaskan Malamute"),
	ANATOLIAN_SHEPHERD_DOG(BreedGroup.WORKING, "Anatolian Shepherd Dog"),
	BERNESE_MOUNTAIN_DOG(BreedGroup.WORKING, "Bernese Mountain Dog"),
	BLACK_RUSSIAN_TERRIER(BreedGroup.WORKING, "Black Russian Terrier"),
	BOXER(BreedGroup.WORKING, "Boxer"),
	BULLMASTIFF(BreedGroup.WORKING, "Bullmastiff"),
	CANE_CORSO_(BreedGroup.WORKING, "Cane Corso "),
	DOBERMAN_PINSCHER(BreedGroup.WORKING, "Doberman Pinscher"),
	DOGUE_DE_BORDEAUX(BreedGroup.WORKING, "Dogue de Bordeaux"),
	GERMAN_PINSCHER(BreedGroup.WORKING, "German Pinscher"),
	GIANT_SCHNAUZER(BreedGroup.WORKING, "Giant Schnauzer"),
	GREAT_DANE(BreedGroup.WORKING, "Great Dane"),
	GREAT_PYRENEES(BreedGroup.WORKING, "Great Pyrenees"),
	GREATER_SWISS_MOUNTAIN_DOG(BreedGroup.WORKING, "Greater Swiss Mountain Dog"),
	KOMONDOR(BreedGroup.WORKING, "Komondor"),
	KUVASZ(BreedGroup.WORKING, "Kuvasz"),
	MASTIFF(BreedGroup.WORKING, "Mastiff"),
	LEONBERGER(BreedGroup.WORKING, "Leonberger"),
	NEAPOLITAN_MASTIFF(BreedGroup.WORKING, "Neapolitan Mastiff"),
	NEWFOUNDLAND(BreedGroup.WORKING, "Newfoundland"),
	PORTUGUESE_WATER_DOG(BreedGroup.WORKING, "Portuguese Water Dog"),
	ROTTWEILER(BreedGroup.WORKING, "Rottweiler"),
	SAINT_BERNARD(BreedGroup.WORKING, "Saint Bernard"),
	SAMOYED(BreedGroup.WORKING, "Samoyed"),
	SIBERIAN_HUSKY(BreedGroup.WORKING, "Siberian Husky"),
	STANDARD_SCHNAUZER(BreedGroup.WORKING, "Standard Schnauzer"),
	TIBETAN_MASTIFF(BreedGroup.WORKING, "Tibetan Mastiff"),;
	private BreedGroup mGroup;
	private String mName;//primary
	private String[] mAlternateNames;//all possible
	Breeds(BreedGroup group, String namePrimary, String... otherNames)
	{
		mGroup = group;
		mName = namePrimary;
		ArrayList<String> names = new ArrayList<String>(otherNames.length + 1);
		names.add(namePrimary);
		for(int i = 0; i < otherNames.length; i++)
		{
			names.add(otherNames[i]);
		}
		mAlternateNames = new String[names.size()];
		mAlternateNames = (String[]) names.toArray(mAlternateNames);
	}
	
	public String getPrimaryName()
	{
		return mName;
	}
	
	public String[] getNames()
	{
		return mAlternateNames;
	}
	
	public BreedGroup getGroup()
	{
		return mGroup;
	}
	
}